version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: stockvn_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ../stockvn-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d stockvn_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always