apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: thehaohcm/stockvn-frontend-ui:0.0.6-amd64
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /config.json
              subPath: config.json
      volumes:
        - name: config-volume
          hostPath:
            path: ./config.json
            type: File
