apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: thehaohcm/stockvn-frontend-ui:0.0.6-amd64
          ports:
            - containerPort: 8080
          env:
          - name: API_URL
            value: "http://207.180.197.79:30000"
